### PR TITLE
Setup nodemailer file

### PR DESCRIPTION
**Pull request by hoduola5**
Setup "nodemailer" file to send email to users

### CODE REVIEW

**Review by xyluz — CHANGES_REQUESTED** [review]
Did you test this? 

Could you have a test email sent from another file that imports the sendEmail.js file?

**Comment by hoduola5** [comment]
I did test it and it worked fine in the same file.

But I haven't tested from another file, I will try that and revert.

**Comment by hoduola5** [comment]
Email can now be sent from another file that imports the sendEmail.js file. 

Kindly check, thanks.

**Comment by hoduola5** [comment]
Can I delete the branches you already merged?

**Pull request merged**
